### ISSUE TITLE
Invalid Elm generated for type definitions using 'allOf'

### ISSUE THREAD

**Issue by abingham** [Parquery/swagger-to#106]
Given this YAML:
```
basePath: /
consumes:
- application/json
info:
  description: An API
  title: An API
  version: '1.0'
definitions:
  MyType:
    properties:
      object_id:
        type: integer
        format: int32
    type: object
  SubType:
    allOf:
      - $ref: "#/definitions/MyType"
      - type: object
        properties:
          size:
            type: integer
            format: int32
    type: object
paths:
  /:
    get:
      operationId: get_foo
      responses:
        '200':
          description: Success
produces:
- application/json
swagger: '2.0'
```
and this command:
```
% python `which swagger_to_elm_client.py` --swagger_path broken.yaml --outdir gen
Generated Elm client code in: gen
```
I'm getting this in my generated Elm:
```
type alias MyType = 
    { objectID : Maybe (Int)
    }


type alias SubType = 
    }
```
The `SubType` declaration is missing it's `size` field and is syntactically incorrect.

**Comment by mristin** [comment]
@abingham we did not implement `AllOf` in swagger-to since Go does not support inheritance. A quick fix would be to simply join the properties without any proper inheritance logic behind it -- but that would be confusing for the reader, wouldn't it?

Is the inheritance a blocking feature for you or only a nice-to-have?

**Comment by abingham** [comment]
This isn't blocking, but I also want to avoid letting tools constrain me too much. I've got several tools that need to work with my spec, and I'd hate to get into a situation where they have mutually incompatible idiosyncracies.

> but that would be confusing for the reader, wouldn't it?
Actually, if I understand what you're saying, that's exactly what tools like swagger-codegen do. Elm doesn't have subclassing either, so the types they generate when `allOf` is involved are just supersets of all the properties. That works just fine for me, and in fact feels quite natural from an Elm point of view.

**Comment by mristin** [comment]
Ok, then let me implement it that way at the swagger <-> intermediate representation level by just making a superset of all the properties with no notion of the inheritance involved. This is also much less work.

**Comment by mristin** [comment]
@abingham could you please check if #116 solves the issue? I did not merge it into master since I can imagine that it would need more fixes. If it works on your schema, I'd say we merge it in as-is. Please inspect also the code in the PR #116, at least the Elm code, to see if that is what you expected.

**Comment by abingham** [comment]
This does seem to work properly. There's still an issue with `allOf` definitions that don't specify a `type`, but I'll create a new issue for that.
