### ISSUE TITLE
ValueError on array

### ISSUE THREAD

**Issue by damoun** [Parquery/swagger-to#73]
Hi,

I used your project on the PetStore API provided by the Swagger team but I've got the following error:

```shell
$ wget https://petstore.swagger.io/v2/swagger.json
$ swagger_style.py --verbose --with_line_number --swagger_path swagger.json
Traceback (most recent call last):
  File "/usr/local/bin/swagger_style.py", line 96, in <module>
    sys.exit(main())
  File "/usr/local/bin/swagger_style.py", line 44, in main
    swagger=swagger, typedefs=intermediate_typedefs, params=intermediate_params)
  File "/usr/local/lib/python3.7/site-packages/swagger_to/intermediate.py", line 590, in to_endpoints
    endpoint = _to_endpoint(method=method, typedefs=typedefs, params=params)
  File "/usr/local/lib/python3.7/site-packages/swagger_to/intermediate.py", line 555, in _to_endpoint
    param = _anonymous_or_get_parameter(original_param=original_param, typedefs=typedefs, params=params)
  File "/usr/local/lib/python3.7/site-packages/swagger_to/intermediate.py", line 489, in _anonymous_or_get_parameter
    return _to_parameter(original_param=original_param, typedefs=typedefs)
  File "/usr/local/lib/python3.7/site-packages/swagger_to/intermediate.py", line 423, in _to_parameter
    PRIMITIVE_SWAGGER_TYPES, original_param.type))
ValueError: Expected type of a parameter to be one of ['string', 'number', 'integer', 'boolean', 'file'], but got: 'array'
```

**Comment by mristin** [comment]
Hi @damoun ,
Thanks for reporting the issue! I'll have a look at the error tonight.

**Comment by mristin** [comment]
Hi @damoun ,
I looked deeper into it. The issue will not be easy to fix, unfortunately. Pet store API uses arrays in query parameters (see the operation `findPetsByStatus` and the parameter `status`). 

When I initially wrote swagger-to, I realized that it would become messy to implement multiple values in query parameters and decided not to support them. We used Uber API as reference where no problems showed up (see https://github.com/Parquery/swagger-to/blob/master/tests/cases/style/general/swagger.yaml).

In my opinion, it would only make sense to rewrite the intermediate representation to support Swagger definitions completely since patching the current implementation for all those unsupported cases would likely end up in a ball of mud. However, since OpenAPI 3.0 was established as a standard in the meanwhile, I am not really sure the rewrite would be worth the effort.

Do you plan to use swagger-to intensively?

**Comment by damoun** [comment]
No, I'm not using swagger-to intensively so I'm fine with this issue, it's only on the PetStore API.

**Comment by mristin** [comment]
@Sasha93 I'd suggest we close the issue as a wont-fix?

**Comment by Sasha93** [comment]
Issue closed as a won't fix.
